name: Deploy IsteNith Website Application

on:
  push:
    branches:
      - source
  pull_request:
    branches:
      - source

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Start the application
        run: npm start

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/source'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out # Update if needed

      - name: Cleanup old deployments
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          keep_files: false
